name: Automatic Releases
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "manzolo/bluetooth-watcher@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Production Build"
          files: |
            app/release/app-release.apk
