name: Automatic Releases
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "svenstaro/upload-release-action@2.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          release_name: "latest"
          prerelease: false
          tag: "${{ github.ref }}"
          file: |
            app/release/app-release.apk
