name: Automatic Releases
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            app/release/app-release.apk
          id: "automatic_releases"
